import { Manrope } from "next/font/google";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const manrope = Manrope({
    subsets: ["latin"],
    preload: true,
    variable: "--font-manrope",
});

const myFont = localFont({
    src: [
        {
            path: "./fonts/BGF/light.otf",
            weight: "100",
            style: "normal",
        },
        {
            path: "./fonts/BGF/light_italic.otf",
            weight: "100",
            style: "italic",
        },
        {
            path: "./fonts/BGF/thin.otf",
            weight: "200",
            style: "normal",
        },
        {
            path: "./fonts/BGF/thin_italic.otf",
            weight: "200",
            style: "italic",
        },
        {
            path: "./fonts/BGF/regular.otf",
            weight: "300",
            style: "normal",
        },
        {
            path: "./fonts/BGF/regular_italic.otf",
            weight: "300",
            style: "italic",
        },
        {
            path: "./fonts/BGF/medium.otf",
            weight: "400",
            style: "normal",
        },
        {
            path: "./fonts/BGF/medium_italic.otf",
            weight: "400",
            style: "italic",
        },
        {
            path: "./fonts/BGF/bold.otf",
            weight: "500",
            style: "normal",
        },
        {
            path: "./fonts/BGF/bold_italic.otf",
            weight: "500",
            style: "italic",
        },
        {
            path: "./fonts/BGF/black.otf",
            weight: "600",
            style: "normal",
        },
        {
            path: "./fonts/BGF/black_italic.otf",
            weight: "600",
            style: "italic",
        },
    ],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    viewport: "width=device-width, initial-scale=1,orientation=landscape",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${manrope.className} ${myFont.className} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
